// Generated by tools/wxl-appearance/SyncClientContract.py. Do not edit.
#pragma once
#include <cstdint>
namespace wxl::appearance {
constexpr uint32_t ClientCatalogId = 3060710526u;
} // namespace wxl::appearance
