// Embedded Ed25519 public key that authorises the extension manifest. GENERATED FILE.
// Copyright (C) 2026 WarcraftXL. GPLv3 (regenerate with `wxl-sign keygen`; do not hand-edit).

#pragma once

#include <cstdint>

/// The manifest-signing public key baked into the DLL. Generated by `wxl-sign keygen`; the
/// matching secret key lives in wxl-signing-key.bin and MUST be kept out of version control.
namespace wxl::security
{
    inline constexpr uint8_t kEd25519PublicKey[32] = {
        0x71, 0x15, 0xc6, 0x6d, 0xf0, 0x07, 0x80, 0xf5,
        0x9c, 0x50, 0x8a, 0xb6, 0x57, 0x8e, 0xae, 0xc9,
        0x72, 0x20, 0x62, 0x6c, 0x13, 0x07, 0xef, 0x2a,
        0xb5, 0x21, 0x2f, 0x2a, 0x32, 0xea, 0x18, 0xd6,
    };

    /// A real signing key is baked in, so production verification is active.
    inline constexpr bool kHasSigningKey = true;
}
